### ISSUE TITLE
Hide trailing hashtags produces error 500 when the post only contains hashtag

### ISSUE THREAD

**Issue by B0pol** [cloudrac3r/bibliogram#72]
```
           ◸―――――――――――――――――――――――――――――――――――――◹
     ···<  |        500. That's an error.        |  >···
           ◺―――――――――――――――――――――――――――――――――――――◿


 ╱  Are you visiting this website? Not sure what's going on?  ╲
 ╲             You might want to come back later.             ╱



TypeError: pug/includes/post.pug:32
    30| 							p.structured-text.description
    31| 								if settings.remove_trailing_hashtags
  > 32| 									+display_structured(post.getStructuredCaptionWithoutTrailingHashtags())
    33| 								else
    34| 									+display_structured(post.getStructuredCaption())
    35| 

Cannot read property 'type' of undefined
    at shouldRemoveLastPart (/home/cloud/bupdate/bibliogram/src/lib/utils/structuretext.js:94:12)
    at removeTrailingHashtags (/home/cloud/bupdate/bibliogram/src/lib/utils/structuretext.js:112:9)
    at TimelineEntry.getStructuredCaptionWithoutTrailingHashtags (/home/cloud/bupdate/bibliogram/src/lib/structures/TimelineEntry.js:116:15)
    at Object.pug_interp [as post] (eval at wrap (/home/cloud/bupdate/bibliogram/node_modules/pug-runtime/wrap.js:1:1), <anonymous>:142:39)
    at Object.eval (eval at wrap (/home/cloud/bupdate/bibliogram/node_modules/pug-runtime/wrap.js:1:1), <anonymous>:401:19)
    at Object.template [as web] (eval at wrap (/home/cloud/bupdate/bibliogram/node_modules/pug-runtime/wrap.js:1:1), <anonymous>:402:94)
    at render (/home/cloud/bupdate/bibliogram/node_modules/pinski/plugins.js:14:47)
    at /home/cloud/bupdate/bibliogram/src/site/api/routes.js:200:12
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
e.g. https://bibliogram.art/p/CAubsdBJBGf

**Comment by cloudrac3r** [comment]
No more errors in 21875a8e838a2e0f4b1cc9b1bfb710c33b4f80cc.
